### ISSUE TITLE
Request duration reported to be less then it's dependency duration

### ISSUE THREAD

**Issue by pakrym** [Microsoft/ApplicationInsights-aspnetcore#370] opened 2017-03-27 16:55 UTC
See https://github.com/aspnet/Home/issues/1955#issuecomment-289507366

**Comment by pharring** [comment] 2017-03-27 17:51
Dupe of #350

**Comment by pharring** [comment] 2017-03-31 22:11
@pakrym @jcsharp I believe this is now fixed. 2.1-Beta1 has just been released.

**Comment by jcsharp** [comment] 2017-04-03 09:46
Yes, now the dependency traces are correlated to the requests and the duration times seem correct. Thank you.

**Closed** 2017-04-03 17:42 UTC
