### ISSUE TITLE
Cannot see SQL statements under SQL Dependency in AI

### ISSUE THREAD

**Issue by patnolan** [microsoft/ApplicationInsights-aspnetcore#705] opened 2018-06-18 06:55 UTC
I have a .Net Framework 4.6.1 API which is referencing a .NET Standard 2.0 assembly for data access.

The .Net Framework 4.6.1 API references Microsoft.ApplicationInsights.AspNetCore 2.3.0-Beta2 and the .NET Standard 2.0 assembly references Microsoft.EntityFrameworkCore.SqlServer 2.1.0.

For some reason in AI the only information I see related to SQL is the following (I do not see any sql statement)

Command
SQL Alias | DatabaseName

Should this scenario currently work? If so, is there anything in particular I need to do to make this work?

**Comment by cijothomas** [comment] 2018-06-18 16:53
SQL statement is not collected for .net core apps. So what you are seeing is the expected behavior.
(even for .net frameworks apps, full sql query is collected by installing profiler - either via StatusMonitor or Azure Extension, but this is not supported for .net core)

**Comment by peter-bozovic** [comment] 2018-06-19 10:38
I had similar problem that I fixed by using custom Logger that sends EntityFramework commands as Telemetry to Application Insights and contains full SQL queries.

Just published the gist to share the code:
https://gist.github.com/peter-bozovic/04a260e517cb3ed4c45b45d0dc21152e

It's probably not available by default for Security/Privacy reasons.

**Comment by cijothomas** [comment] 2018-06-21 22:47
It looks like sql command should be captured:
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/SqlClientDiagnostics/SqlClientDiagnosticSourceListener.cs#L106

Need to confirm.

**Comment by cijothomas** [comment] 2018-07-10 00:14
.Net Core app do support collecting full SQL Statements. I was wrong when I mentioned earlier that sql statements are not collected for .net core apps!

@patnolan What is the sdkVersion for the dependencies you see (where you dont see full sql query). Is it starting like "rdddsc".. ?

**Comment by sadjadbp** [comment] 2018-07-25 06:45
@cijothomas the sdkVersion for me is "rddf:2.6.4-28401" and don't see the full SQL statements, which column should have that?

**Comment by sadjadbp** [comment] 2018-07-25 06:47
Seem like it only log the stored proc name other that nothing else is getting logged.

```csharp
var commandName = command.CommandType == CommandType.StoredProcedure
    ? command.CommandText
     : string.Empty;

dependencyName = string.IsNullOrEmpty(commandName)
    ? string.Join(" | ", connection.DataSource, 
    : string.Join(" | ", connection.DataSource, connection.Database, commandName);
```

**Comment by cijothomas** [comment] 2018-07-25 16:50
If the sdk version is starting with 'rddf', then you wont see sql statements. Its available if prefix is "rddp" or 'rdddsc`. 
What is the type of application you have - .net frameowkr or .net core?

**Comment by sadjadbp** [comment] 2018-07-25 17:18
It's .net framework based asp.net core project

**Comment by cijothomas** [comment] 2018-07-25 17:55
Do you mean an asp.net core project, which is targetting .net framework? If thats the case, then to get full SQL query, you need to install StatusMonitor in your machine.
Where are you running the application now? 

(I need to check if this is a fully sopported scenario as well)

**Comment by cijothomas** [comment] 2018-07-25 19:05
@sadjadbp Can you install Status Monitor and then try again to see if you are getting full sql statements ?

**Comment by sadjadbp** [comment] 2018-09-02 05:08
@cijothomas installed Status Monitor and this is what I got from status monitor

![image](https://user-images.githubusercontent.com/6307366/44952405-830c8100-ae33-11e8-8259-5a57bceccc90.png)

**Comment by cijothomas** [comment] 2019-05-31 17:30
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies#advanced-sql-tracking-to-get-full-sql-query Closing as SQL query is captured in asp.net core app always.

**Closed by cijothomas** 2019-05-31 17:30 UTC
Labels: question
