### ISSUE TITLE
UseApplicationInsights method doesn't support appsettings{environment}.json override

### ISSUE THREAD

**Issue by maybeleo** [Microsoft/ApplicationInsights-aspnetcore#464] opened 2017-06-01 11:26 UTC
Hi all...

There is an issue I've trapped recently using default AAI configuration method for asp.net core applications... The `ApplicationInsightsWebHostBuilderExtensions.UseApplicationInsights(this IWebHostBuilder webHostBuilder)` doesn't use environment-specific appsettings.xxx.json file making it impossible to have different instrumentation keys for different environments. This can be worked around, of course, but looks not that pretty. ILSpy shows there is finally such code used:

`ApplicationInsightsExtensions.AddTelemetryConfiguration(new ConfigurationBuilder().SetBasePath(this.hostingEnvironment.ContentRootPath).AddJsonFile("appsettings.json", true).AddEnvironmentVariables().Build(), options);`

in the `DefaultApplicationInsightsServiceConfigureOptions` class, which differs from the typical configuration building pattern like

`new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();`

Thanks...

**Comment by dnduffy** [comment] 2017-06-01 17:32
This is a duplicate of #449 and has already been fixed.  The fix will be in the 2.1.0 stable release.

**Closed by dnduffy** 2017-06-01 17:32 UTC

**Comment by hc183** [comment] 2018-01-05 21:56
Hi,
I am getting duplicate entry in Azure for exceptions.
In my Configure method in startup.cs have following code which is my custom global exception handler which uses telemetry.trackexception to log exception details along with POST request's body as custom property.
app.UseExceptionHandler((options) => GlobalExceptionWrapper.HandleException(options));

And in my Program.cs I have following code.. 
var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .UseApplicationInsights()
                .Build();

            host.Run();



so wondering what's wrong going on here? And what's the best approach to handle the exception in ASP.Net Core 2.0 Web API project with Application Insights? Is there any document or  sample for Web API project? 
This ([https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling]) is for MVC  error handling but what's the best way for web api?
