### ISSUE TITLE
Disable AdaptiveSampling for stateless service fabric services without IServiceCollection

### ISSUE THREAD

**Issue by ththiem** [microsoft/ApplicationInsights-aspnetcore#855] opened 2019-03-22 21:47 UTC
Currently .NET Core services utilizing Service Fabric do not utilize any Startup, ConfigureServices, or IServiceCollection. App Insights is enabled and configured manually like in the following example, and as a result adaptive sampling is on by default:

https://github.com/yantang-msft/service-fabric-application-insights-example/blob/master/StatelessBackend/StatelessBackend.cs

Is there no way to disable adaptive sampling in this scenario?

**Comment by cijothomas** [comment] 2019-03-22 21:52
Adaptive sampling is not enabled by default. Infact, no sampling is enabled by default in a console app. So could you clarify where did you see adaptive sampling being enabled by default? 

(if you are using asp.net core web app and enable application insights with extension method, then Adaptive sampling is enabled by default, but your sample is not Asp.net core web app)

**Comment by ththiem** [comment] 2019-03-22 21:59
Application Insights itself is reporting that sampling is enabled
![image](https://user-images.githubusercontent.com/15839533/54855261-ed432100-4cb2-11e9-86cc-92cfe9e3791d.png)

And there is no ingestion sampling
![image](https://user-images.githubusercontent.com/15839533/54855317-1bc0fc00-4cb3-11e9-9ab6-d23f03a9197c.png)

**Comment by cijothomas** [comment] 2019-03-22 22:04
are you sending data to the same ikey from multiple apps? or is it from ingestion sampling?

If you create TC yourself, then there is no sampling enabled. When you do TelemetryConfiguration.CreateDefault(), what you get is a TC with no sampling procesors and almost no telemetry initialziers. You need to add everything manually. including sampling if required.

**Comment by ththiem** [comment] 2019-03-22 22:08
There is only 1 app, and as seen above ingestion sampling is disabled. The example I linked is also not calling CreateDefault() anywhere. Unless you think this line

`TelemetryConfiguration.Active.TelemetryInitializers.Add(
				FabricTelemetryInitializerExtension.CreateFabricTelemetryInitializer(this.Context)
			);`

Is doing something behind the scenes, which I'm not sure what it is doing for lack of documentation, I am not setting any sampling anywhere.

**Comment by cijothomas** [comment] 2019-03-22 22:10
1. https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling#how-do-i-know-whether-sampling-is-in-operation Follow this and confirm sampling is taking place.
2. Do you have ApplicationInsights.Config file in the app folder?
3. .Active will create a bare minimum instance internally. (bare minimum => no sampling or any other processors)

Share a minimal repro and i can take a look further.

**Comment by ththiem** [comment] 2019-03-22 22:18
We do not have any ApplicationInsights.Config in any projects.

Most of the entries from the query show 100 retainedpercentage, but there are several points where it is not the case:
![image](https://user-images.githubusercontent.com/15839533/54855933-81ae8300-4cb5-11e9-8655-8482accb90b1.png)
![image](https://user-images.githubusercontent.com/15839533/54855951-93902600-4cb5-11e9-8da0-5ca73f7b1340.png)
![image](https://user-images.githubusercontent.com/15839533/54855964-9ee35180-4cb5-11e9-96d6-efd412916c28.png)
![image](https://user-images.githubusercontent.com/15839533/54855974-a4d93280-4cb5-11e9-82d4-f42e6c523e37.png)

What does it mean when specific snapshots show less than 100, but most of them show 100?

**Comment by cijothomas** [comment] 2019-03-22 22:51
The screenshot you shared shows sampling is occuring. So not a bug in portal :) Thanks for confirming this much. (change by bin(timestamp, 1h) to 1d or more to see consolidated data. Multiple entries is from separate hours_

Now to dig more - can you put a break point in your app, and inspect TC.Active? it'll tell what processors are present in the config.

This code is not complete as there could be other pieces of code adding sampling to TC.Active.
https://github.com/yantang-msft/service-fabric-application-insights-example/blob/master/StatelessBackend/StatelessBackend.cs

Without seeing full code, I cannot suggest how to remove sampling.

**Comment by ththiem** [comment] 2019-04-01 22:00
Sorry haven't been able to return to this issue over the past week.

Inspecting telemetry configuration only shows 1 processor, the PassThroughProcessor. So sampling is not happening as far as I can tell, and recently we have stopped having the messages related to sampling appear in app insights search, and the analytics query is also not showing sampling lately. Not sure what is going on with that anymore.

Instead a new issue has surfaced today where telemetry data is simply missing altogether despite the other sources confirming sampling is not happening, and throttling also doesn't appear to be happening either. But we have telemetry items that are orphaned; they show up at the bottom of an operation transaction but their parent operation(s), including dependencies, are missing.

**Comment by cijothomas** [comment] 2019-04-10 17:19
@ththiem Please confirm if you still have issues with sampling happening automatically? For other issue please open a new issue.

**Comment by cijothomas** [comment] 2019-07-16 16:05
Closing. Re-open or create new issue as needed.

**Closed by cijothomas** 2019-07-16 16:05 UTC
