### ISSUE TITLE
Application Insights automatically injecting Javascript into <head>

### ISSUE THREAD

**Issue by knightmeister** [Microsoft/ApplicationInsights-aspnetcore#609] opened 2018-02-25 01:47 UTC
See also post on Stackoverflow - not by me - the only answer did not work for me.
https://stackoverflow.com/questions/47681778/controlling-application-insights-javascript-injection

## Repro Steps
1.  In program.cs, add `.UseApplicationInsights("YOUR KEY HERE")`

##  Actual Behavior
Observe the following fragment is now automatically output in your <head> section, before the closing </head>

````
<script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function i(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s="AuthenticatedUserContext",h="start",c="stop",l="Track",a=l+"Event",v=l+"Page",y=u.createElement(o),r,f;y.src=config.url||"https://az416426.vo.msecnd.net/scripts/a/ai.0.js";u.getElementsByTagName(o)[0].parentNode.appendChild(y);try{t.cookie=u.cookie}catch(p){}for(t.queue=[],t.version="1.0",r=["Event","Exception","Metric","PageView","Trace","Dependency"];r.length;)i("track"+r.pop());return i("set"+s),i("clear"+s),i(h+a),i(c+a),i(h+v),i(c+v),i("flush"),config.disableExceptionTracking||(r="onerror",i("_"+r),f=e[r],e[r]=function(config,i,u,e,o){var s=f&&f(config,i,u,e,o);return s!==!0&&t["_"+r](config,i,u,e,o),s}),t
        }({
            instrumentationKey: 'YOUR GUID'
        });

        window.appInsights=appInsights;
        appInsights.trackPageView();
        
    </script>
````
In addition to this, my ASPNETCORE_ENVIRONMENT variable is set to Development, which I would have thought would stop all AI telemetry.

## Expected Behavior
Per documentation, I should be able to control injection of the JavaScript snippet with

````
@using Microsoft.ApplicationInsights.AspNetCore
@inject JavaScriptSnippet snippet
....
 @Html.Raw(snippet.FullScript)
</head>
````

## Version Info 
SDK Version : Reproducible with metapackage and also after adding Microsoft.ApplicationInsights.AspNetCore 2.2.1 
.NET Version : NET Core 2.0.5 (using Metapackage Microsoft.AspNetCore.All)	 						
Hosting Info (IIS/Azure WebApps/ etc) : Visual Studio / Kestrel

**Comment by bjr001** [comment] 2018-02-25 22:51
Obviously I'm not the only one having some struggle with this.

It seems there are two options to stop AI telemetry as you can see [here](https://github.com/aspnet/Home/issues/2051):
- by setting environment variable ASPNETCORE_preventHostingStartup to true
- by altering TelemetryConfiguration within the Configure method of Startup class

Both have there own drawbacks as you can read in the link above. There you will also find some information that AI is tightly coupled with VS. So from my understanding VS itself places the javascript snippet by its own as soon as you add the AI InstrumentationKey to your appsettings.json. 

A third options seems to be in the latest preview of VS (15.6) where you can disable AI locally within the tools option.

Nevertheless I think the documentation is pretty misleading. I would almost say it's complete useless....

**Comment by cijothomas** [comment] 2018-03-02 07:55
@knightmeister ApplicationInsights does not inject Javascript snippet itself. Its injected by  Visual Studio if you launch the app from within Visual Studio. You can always control JavaScript snippet injection yourself.

**Comment by cijothomas** [comment] 2018-03-02 07:56
@knightmeister 

> In addition to this, my ASPNETCORE_ENVIRONMENT variable is set to Development, which I would have thought would stop all AI telemetry.

**Comment by cijothomas** [comment] 2018-03-02 08:01
@bjr001 As mentioned in the linked issue, VS is tightly integrated with application insights experience - based on user feedback, however VS is providing new feature to disable application insights locally.

Can you point me to the documentation which is misleading. I am more than happy to correct the documentation.
The following 2 are the documentation I am aware of. Please let me know if you find misleading information here.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-for-a-ASP.NET-CORE-2.0-WebApp 
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net-core

**Comment by SergeyKanzhelev** [comment] 2018-03-02 17:42
@cijothomas asp.net core SDK injects JavaScript snippet. See the use of https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/12cb0cd96c83115eeb16d7b2711c5ddb73c9e69c/src/Microsoft.ApplicationInsights.AspNetCore/ApplicationInsightsJavaScript.cs#L12 in the code

**Comment by cijothomas** [comment] 2018-03-02 17:55
@SergeyKanzhelev I meant SDK does not do this part by itself:
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net-core#page-view-load-time
user has to manually modify the cshtml to get the snippet (which is made available by sdk). but if you launch app from VS, then the snippet is inserted automaticaly.

**Comment by cijothomas** [comment] 2018-03-06 07:10
Note that if the app is deployed to Azure Web App, and then AI is enabled from WebApp - in this scenario also entire AI (including javascript) is 'lightup' automatically. (this is **only if AI extension is installed** in WebApp)

**Comment by cjnaude** [comment] 2018-03-21 08:34
@cijothomas I followed the github guide ([https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net-core#page-view-load-time](url)), without adding the javascript snippet, and when my app is on azure the AI javascript snippet is still being injected. Do you have any advice on how to disable it? I did not enable AI from the web app in azure.

**Comment by cijothomas** [comment] 2018-03-21 14:09
@cjnaude Can you list the exact steps you followed? 
Do you see javascript snippet when you run locally (outside of visual studio) ? Or do you see it only when running on Azure Web Apps?

**Comment by cjnaude** [comment] 2018-03-22 07:14
@cijothomas 1. Created the Application Insights resource on Azure
2. Already had the package included through <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
3. Added the instrumentation key to appsettings.json
4. Added UseApplicationInsights to the WebHostBuilder instance
5. Deployed to Azure

The javascript does not appear when I run locally (through VS Code) and it has not been added to the published view, so its definitely being injected by Azure.
I've tried adding APPINSIGHTS_JAVASCRIPT_ENABLED = false to the web app, but that made no difference.

**Comment by p-** [comment] 2018-03-23 15:36
@cijothomas:
> entire AI (including javascript) is 'lightup' automatically. (this is only if AI extension is installed in WebApp)

As far as I saw AI is indirectly referenced when using `Microsoft.AspNetCore.All`, no?

An working way to disable the AI JavaScript from being injected when deploying to Azure was setting 'Prevent Hosting Startup' to true, like:

```
WebHost.CreateDefaultBuilder(args)
    .UseSetting(WebHostDefaults.PreventHostingStartupKey, "true")
```

**Comment by cjnaude** [comment] 2018-03-26 11:38
@p- That did the trick, thanks!

**Comment by electricessence** [comment] 2018-05-15 21:29
Ok so I'm a bit confused here.  Is there a way to have your cake and eat it too?
1) I like that it gets auto injected.
2) I hate that I can't control what order it gets injected in so I can add configuration after init.

How can I simply tell Visual Studio not to add this when I launch it?

**Comment by cijothomas** [comment] 2018-05-15 22:09
This env variable, ASPNETCORE_PREVENTHOSTINGSTARTUP=true, will prevent VS auto 'onboarding' application insights when running from VS.

**Comment by electricessence** [comment] 2018-05-15 22:15
@cijothomas what other consequences arise by doing that?

**Comment by philwade** [comment] 2019-02-14 18:55
I'd like to chime in and say this really needs to be fixed. I just lost a morning to it and I'm not very happy about it. Magically injecting a script tag into an application *but only in certain weird circumstances* and then having the only way to turn it off be through a weird, seemingly unrelated configuration value? Not great.

**Comment by cijothomas** [comment] 2019-02-14 20:57
@philwade Can you describe exactly whats the issue you are facing? Did you publish asp.net app to Azure Web App and see tht js snippet is injected automatically?  That is not the expected behavior. jssnippet or sdk is injected in App Service only if you enable application insights in webapp explicitly - nothing is turned on by default. If you experienced otherwise, I can investigate.

**Comment by philwade** [comment] 2019-02-15 15:05
@cijothomas I have an azure app service with insights turned on, so it sounds like I'm seeing the expected behavior. However, I don't like the magic injection of the script tag. If you're going to do something automatically for people, you should make it very clear in the documentation and make it super obvious how to turn it off. As it is, this bug report is the only place I could find any information about this behavior and the only place that I could find that told me how to disable it. Additionally, `WebHostDefaults.PreventHostingStartupKey` is seemingly unrelated to what it's actually doing and I'm afraid that setting it to true will cause additional side effects that won't rear up until later on in the application's life. This whole feature needs a rework.

**Comment by cijothomas** [comment] 2019-02-15 17:30
@philwade The documentation was already updated to describe this behavior. If you don't want injection of scripts - you can turn off application insights in app service, and onboard via nuget in build time.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps


WebHostDefaults.PreventHostingStartupKey - this is unrelated to azure web apps scenario. its for visual studio.

**Comment by philwade** [comment] 2019-02-15 18:21
@cijothomas I do not see where in that page of documentation it says anywhere "we will inject a script tag into the head of your documents". On the contrary, it links to this page: https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript which instructs you to manually insert the same javascript into your application. If you followed the directions on the initial page then tried to add the javascript, you would end up with two instantiations of app insights and questions about where the script tag was coming from, like I did.

**Comment by cijothomas** [comment] 2019-02-15 18:42
![image](https://user-images.githubusercontent.com/5232798/52877114-f4a06900-310d-11e9-8cad-8158544ef59a.png)
I was referring to the above section:

I agree that js injection should back off, if snippet is already detected. This is a bug. (for server side telemetry, extension detects the existing presence of application insights, and backs-off. similar should be done for js snippet as well. I will open an issue tracking it.)

**Comment by cijothomas** [comment] 2019-02-15 19:04
btw - if you find issues in docs, pleae feel free to open issue about the docs. there is a active team looking at those issues and addressing them.

**Comment by cijothomas** [comment] 2019-04-09 18:25
CLosing this as new docs cover how to turn on and off js snippet injection.

**Closed by cijothomas** 2019-04-09 18:25 UTC
