### ISSUE TITLE
Request duration is incorrect in netcoreapp1.1

### ISSUE THREAD

**Issue by Yshayy** [Microsoft/ApplicationInsights-aspnetcore#402] opened 2017-04-21 18:35 UTC
Hi, 
we've been using application insights for some time and leveraged many of its capabilites.
Yet, since the transation to asp.net core (this middleware with netcoreapp1.1 targeting app) we're getting scaled down numbers for request duration. (around 1/100, so 1000ms is actually ~10ms).
We are running our application with the office asp.net runtime docker image.

Any ideas what can cause it and how we can solve it? (other than multipling all the request duration numbers in our alert rules or dashboards)

Thanks.

**Comment by dnduffy** [comment] 2017-04-21 20:17
Are you targeting full framework (e.g. net451) from your .NET Core app?
We just found a bug two days ago where the configuration options to disable adaptive sampling are not being honored.  I'm still investigating it but plan to have it fixed in the 2.1-beta2 release next week.

**Comment by Yshayy** [comment] 2017-04-21 20:20
Yes, that's the definition in the csproj file:
```
<PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81</PackageTargetFallback>
  </PropertyGroup>
```

**Closed** 2017-04-21 20:20 UTC

**Comment by Yshayy** [comment] 2017-04-21 20:25
Can you share details to the root cause of the problem? (or link to the relevant issue/pr)
Thanks.

**Comment by pharring** [comment] 2017-04-21 22:45
#343 had the fix. Root cause was a bug in the Http diagnostic listener which assumed non-overlapping requests.

**Comment by Yshayy** [comment] 2017-04-22 04:11
Interesting.
Although I'm not sure it's the same problem since get the right results but on different unit scale. (we also collect the metrics to graphite, so we have something to compare against)
