### ISSUE TITLE
ApplicationInsightsLogger

### ISSUE THREAD

**Issue by ShrenikOne** [Microsoft/ApplicationInsights-aspnetcore#511] opened 2017-08-02 04:50 UTC
I come across recently that AspNetCore nuget package contains a ApplicationInsightsLogger. which implements Microsoft.Extensions.Logging.ILogger. I truly feel that these logger should be independent of AspNetCore. We in our project actually implemented ApplicationInsightsLogger which we used across different types of applications, which include AspNetCore Web, Api, Web Jobs, Excel, Word Add-In and Shell Extension. These is great if its coming directly from horses mouth :), So i would request if you can release this logger as independent package.

Also based on code understanding i have couple of observation:
1. Currently ILogger.log method expect Formatter, but generally you work with multiple Loggers like NLog, Debug, Console, Events etc. Its unlikely that everything need same formatter, i would say its design limitation on ILogger interface, but never less there is still make it work better way. 
2. Another observation that its trying to cast TState as IReadOnlyList<KeyValuePair<string, object>>, Rather assuming that State object is this specific type, which also bring some challenge when work across multiple loggers and their formatting if any.

I would suggest below: Current code from "Master" branch looks like below:
```csharp
public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
{
	if (this.IsEnabled(logLevel))
	{
	    //// Line suggesting to change
		var stateDictionary = state as IReadOnlyList<KeyValuePair<string, object>>;
		if (exception == null)
		{
		    //// Line suggesting to change
			var traceTelemetry = new TraceTelemetry(formatter(state, exception), this.GetSeverityLevel(logLevel));
			.............
		}
		else
		{
			var exceptionTelemetry = new ExceptionTelemetry(exception);
			//// Line suggesting to change
			exceptionTelemetry.Message = formatter(state, exception);
			..............
		}
	}
}
```

Instead of above: I did small modification in ApplicationInsightsLogger and creator of logger take this as input from consuming application and pass on.
i.e. Introduce two Func as input like below:
```csharp
Func<dynamic, Exception, string> messageCreator;

Func<dynamic, IReadOnlyList<KeyValuePair<string, object>>> stateConverter;
```
Modified code of Logger Method is now like below:
```csharp
public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
{
	if (this.IsEnabled(logLevel))
	{
	    //// Changed line
		var stateDictionary = (state as IReadOnlyList<KeyValuePair<string, object>>) ?? this.stateConverter?.Invoke(state);
		if (exception == null)
		{
		    //// Changed line
			var traceTelemetry = new TraceTelemetry(**this.messageCreator?.Invoke(state, exception) ?? formatter(state, exception)**, this.GetSeverityLevel(logLevel));
			...................
		}
		else
		{
		    //// Changed line
			var exceptionTelemetry = new ExceptionTelemetry(exception);
			exceptionTelemetry.Message = **this.messageCreator?.Invoke(state, exception) ?? formatter(state, exception);**
			................
		}
	}
}
```

Now with this change, its much easier to control message format, which comes-up in Application Insights Portal and don't need to rely on and shift ounce to consuming application to create state dictionary.

Thanks,

**Comment by pharring** [comment] 2017-08-02 13:51
This is mostly a duplicate of #507, but with some suggested enhancements.

**Comment by ShrenikOne** [comment] 2017-08-03 09:18
I have code, can i go ahead and create PR?

**Comment by pharring** [comment] 2017-08-03 15:02
@ShrenikOne I'm not actually a maintainer, but here's my advice:

If it's a PR for the enhancements you suggested then yes, you can create a PR here. Please include updated tests that cover your enhancement.

If it's a PR for moving logging to a separate package, then you'll first need a PR in the https://github.com/Microsoft/ApplicationInsights-dotnet-logging repo and then (maybe after that is approved) a corresponding change in this repo to remove the existing logger.
Also, please also coordinate with @cwe1ss since he indicated he might also be working on it: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/507#issuecomment-319311215

**Comment by SergeyKanzhelev** [comment] 2017-08-03 16:25
@ShrenikOne If you want to contribute - please send a PR to https://github.com/Microsoft/ApplicationInsights-dotnet-logging repo as @pharring suggests

**Comment by cijothomas** [comment] 2019-04-09 18:26
closed as logging is now available as standalone package.

**Closed by cijothomas** 2019-04-09 18:26 UTC
Labels: duplicate
