### ISSUE TITLE
Application level props do not decorate child dependencies

### ISSUE THREAD

**Issue by nulltoken** [microsoft/ApplicationInsights-aspnetcore#428] opened 2017-05-04 10:46 UTC
**Version:** 2.1.0-beta2

Hello. The tests below fails. The request telemetry is correctly decorated with an application level property. However, its dependency isn't. 

Is that expected (_Desperately hoping that is NOT the case_ :wink:)?

```csharp
[Fact]
public void ApplicationLevelPropertyDecoratesChildDependency()
{
    InProcessServer server;
    const string propName = "AppLevelProp";
    const string propValue = "Hello Ma, I'm on GitHub!";

    using (server = new InProcessServer(assemblyName, InProcessServer.UseApplicationInsights))
    {
        var tc = server.ApplicationServices.GetService(typeof(TelemetryClient)) as TelemetryClient;
        Assert.NotNull(tc);

        tc.Context.Properties[propName] = propValue;

        using (var httpClient = new HttpClient())
        {
            var task = httpClient.GetAsync(server.BaseHost + "/");
            task.Wait(TestTimeoutMs);
        }
    }

    var telemetries = server.BackChannel.Buffer;

    Assert.True(telemetries.Count >= 2);
    var requestTelemetry = telemetries.OfType<RequestTelemetry>().Single();
    var dependencyTelemetry = telemetries.OfType<DependencyTelemetry>().Single();

    Assert.True(requestTelemetry.Context.Properties.ContainsKey(propName));
    Assert.Equal(propValue, requestTelemetry.Context.Properties[propName]);

    Assert.True(dependencyTelemetry.Context.Properties.ContainsKey(propName)); // Fails :(
    Assert.Equal(propValue, dependencyTelemetry.Context.Properties[propName]);
}
```

**Comment by nulltoken** [comment] 2017-05-11 12:03
_kind bump_ ?

Would this issue be badly worded or not clear, I'd be happy to enhance it. However, some feedback would be really appreciated.

**Comment by dnduffy** [comment] 2017-05-11 15:20
@nulltoken, no worries, it's clearly worded, we'll get to this as soon as we can.

**Comment by nulltoken** [comment] 2017-06-06 11:59
Repro'd in `2.1.0-beta5`

**Comment by nulltoken** [comment] 2017-07-03 09:27
@dnduffy Now that 2.1.0 is released, any chance that this topic may be triaged?

**Comment by dnduffy** [comment] 2017-07-03 16:45
It would appear that a different context got used by the dependency collector.  Since that is in another package this might not be straightforward to fix.

**Comment by dnduffy** [comment] 2017-07-05 23:08
@nulltoken Can you use a TelemetryInitializer to accomplish the same thing?  Using a TelemetryInitializer is how we would normally do this kind of functionality.

**Comment by nulltoken** [comment] 2017-07-06 07:46
@dnduffy Thanks for the feedback. I'm somehow puzzled:

 - This usage is described in the [wiki](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Configure#add-application-level-context-properties)

    >     You may want to set additional properties on all telemetry data
    >     your application reports. Since it's a global setting you need to
    >     do it in "Configure" method of your application:

    ```
    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerfactory)
    {
         app.ApplicationServices.GetService<TelemetryClient>().Context.Properties["Environment"] = env.EnvironmentName;
    }
    ```

- This works for some other kind of telemetry data. Configured app level props eventually decorate tracking of custom dependencies, events and logs.

Is it because the design is now in flux and TelemetryInitializer will be the only way to achieve this down the road?

**Comment by nulltoken** [comment] 2017-08-19 20:06
@dnduffy _Bump?_ Sorry if this looks like I'm hassling you over this issue. That's definitely not the case. Just willing to get a clearer view of how I should properly implement this with regards to the overall design of this product.

**Comment by nulltoken** [comment] 2017-09-30 11:47
@dnduffy 

![image](https://user-images.githubusercontent.com/92363/31045517-c4fdd192-a5e5-11e7-9cf2-19b171282633.png)

**Comment by nulltoken** [comment] 2017-11-06 20:05
For what it's worth, 2.2.0-beta1 exposes the same behavior. Both Http and Sql dependencies aren't decorated with application level properties.

/cc @cijothomas

**Comment by cijothomas** [comment] 2018-06-08 20:56
@nulltoken I was looking at old unanswered issues and came across this. Sorry for the delay.
The issue is that the `TelemetryClient` instance from DI is NOT used by `DependencyTrackingTelemetryModule`. It instead creates own instance, hence modifying the instance from DI has no effect for dependencies.
RequestCollectionTelemetryModule on the other hand uses the instance from DI, so any modifications would have an effect.
This is a system bug and we'll address it in future. 

Until then, your workaround would be to write a `TelemetryInitializer` yourself to attach any property to all the telemetry item.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Custom-Configuration#configure-telemetry-initializers

**Comment by nulltoken** [comment] 2018-10-10 12:17
@cijothomas Thanks for the feedback (and sorry for my late answer). I indeed implemented a TelemetryInitializer as a workaround.

**Comment by cijothomas** [comment] 2019-05-30 17:34
Closing this issue. The correct way to add custom props is by using TelemetryInitializer in all official docs.

**Closed by cijothomas** 2019-05-30 17:34 UTC
Labels: bug, composite-apps
