### ISSUE TITLE
Log UserName and IP with Custom Properties in Application Insight .Net Core 2.1

### ISSUE THREAD

**Issue by imeya** [microsoft/ApplicationInsights-aspnetcore#771] opened 2018-10-18 09:32 UTC
how to log UserName and IP as custom properties in app insights?

in my custom telemetry initializer, I used:

requestTelemetry.Context.Properties.Add("UserName", _httpContextAccessor.HttpContext.User.Identity.Name);

requestTelemetry.Context.Properties.Add("InternalIP", requestTelemetry.Context.Location.Ip);

But always have a null value.

**Comment by imeya** [comment] 2018-10-19 00:58
as per my test, if it has a null value, then the property is not added. But if I hardcode a value for it, the custom property can be added.

**Comment by bdschaap** [comment] 2018-11-27 01:07
I believe I am encountering the same problem.  I have Windows authentication enabled and anonymous access disabled.  I am authenticated within the controller code but the telemetry initializer code is no longer authenticated (_httpContextAccessor.HttpContext.User.Identify.IsAuthenticated = False).  I did notice that if I make a SQL call inside the controller then dependency telemetry is generated and it _is_ authenticated.  

Looking into it further I can see that in the case of the simple request the telemetry initializer is called _after_ the request completes.  However, in the case of the request that makes a SQL call the dependency event's telemetry initializer is called _before_ the request completes.

**Comment by cijothomas** [comment] 2019-05-30 17:36
closing as no action needed for this sdk.

**Closed by cijothomas** 2019-05-30 17:36 UTC

**Comment by bdschaap** [comment] 2019-05-30 17:41
@cijothomas I was wondering if you suspect that this issue is caused by something outside of the App Insights SDK.  Do you know which repo I should open the issue with?

Thanks!

**Comment by cijothomas** [comment] 2019-05-30 17:46
_httpContextAccessor.HttpContext.User.Identity.Name  -- this code is not application insights specific.  If it returns null, then no property is added. The original post confirm that hardcoding value works, - hence i said its no a bug about application insights telemetry initializer not working.

@bdschaap I see you have a different?related question. Can you open a new issue to discuss it.
