### ISSUE TITLE
Dependency Clash with WindowsAzure.Storage

### ISSUE THREAD

**Issue by frontegi** [Microsoft/ApplicationInsights-aspnetcore#494] opened 2017-07-11 23:15 UTC
Hi Team, 
I just spent 4 hours trying to figure out why a class of mine handling with Azure Storage started giving some authentication Exception.
My piece of code worked for an entire month without issues.
![screenshot_4](https://user-images.githubusercontent.com/10157050/28094627-1bd1f55c-669e-11e7-986f-114b492a609a.jpg)
But suddenly it started to give this damn exception from the WindowsAzure.Storage 8.1.4 library :

```
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Bla.Bla.MyController.UploadFilesPost (Bla) in 82946.8163ms
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
Microsoft.WindowsAzure.Storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext() in C:\Program Files **(x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Core\Executor\Executor.cs:line 315**
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.<>c__DisplayClass75_0.<<ExistsAsync>b__0>d.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Blob\CloudBlob.cs:line 452
--- End of stack trace from previous location where exception was thrown ---
```

I isolated previous days changes using VSTS online history, and i found out that the only thing done was to upgrade from ApplicationInsights.AspnetCore 2.0.1 to 2.1.0 (it was stable...) .
## Rolling back solved the issue

Now, I don't know if the problem is in my code ( don't think so) or in ApplicationInsights 2.10 nor in WindowsAzure.Storage 8.1.4 . However, they  don't really work well together. Probably  my configuration is unlucky. I don't know.
My current dependencies are:
![screenshot_5](https://user-images.githubusercontent.com/10157050/28094819-4de04b74-669f-11e7-8a69-276491d4cd51.jpg)

Hope this however can help someone suddenly stuck with Azure Storage without any reason.
Regards

Giulio Fronterotta

**Comment by pharring** [comment] 2017-07-11 23:22
Dupe of #438 
There is a hotfix on the way. You will want to install version 2.1.1 when it is available.
Otherwise, there's a workaround listed at https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/416#issuecomment-298496914

**Comment by frontegi** [comment] 2017-07-11 23:46
Thank you Pharring.

**Comment by cijothomas** [comment] 2017-07-13 18:25
@frontegi 2.1.1 hotfix release is on nuget.org. Please update. Sorry for the mess it caused.

**Closed by cijothomas** 2017-07-13 18:25 UTC
