### ISSUE TITLE
Application Insights Profiling in .NET Core does not work when using 'Microsoft.ApplicationInsights.AspNetCore'

### ISSUE THREAD

**Issue by gckeller-ps** [Microsoft/ApplicationInsights-aspnetcore#847] opened 2019-02-27 22:10 UTC
## Repro Steps
1. Follow the steps in this article: https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-with-Application-Insights-for-ASP.NET-Core 
2. Deploy to an App Service / Web App on Linux or Windows
3. Observe your exceptions in Application Insights. 

##  Actual Behavior
The following exceptions occur:
Hosting startup assembly exception Could not load file or assembly 'DiagnosticServices.HostingStartup, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. 

Hosting startup assembly exception Could not load file or assembly 'StartupBootstrapper, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. 

The library required in order to resolve this issue has the following issue which precludes adding the Package Reference: https://github.com/NuGet/Home/issues/6892.  I was able to identify the root cause of this issue as described in the aforementioned link.

## Expected Behavior
Application Insights should not throw exceptions on Startup and profiling should work properly

## Windows Resolution
Installing the Application Insights Profiling Site Extension works on Windows (framework dependent).  This does not work on Linux as Linux does not support Site Extensions and I don't believe it works deployed to Windows (self-contained).  @cijothomas Was helpful in guiding me to enter this new issue

## Version Info 
.NET Version : .NET Core 2.2					
How Application was onboarded with SDK : Visual Studio
OS : Linux or Windows
Hosting Info : Azure App Service / Web App

**Comment by gckeller-ps** [comment] 2019-02-27 22:13
Another item of note.  I don't believe the Windows resolution works unless you deploy as "framework-dependent".  It does not work if deployed as "Self-contained"

**Comment by cijothomas** [comment] 2019-02-27 22:44
Microsoft.ApplicationInsights.AspNetCore does not depend on Microsoft.ApplicationInsights.AzureWebSites.

Can you share your package references, and how you have enabled the SDK?

**Comment by gckeller-ps** [comment] 2019-02-27 22:52
> Microsoft.ApplicationInsights.AspNetCore does not depend on Microsoft.ApplicationInsights.AzureWebSites.
> Can you share your package references, and how you have enabled the SDK?

I am not currently using this but rather the site extension deployed on Window because this doesn't works; however, the client wants to deploy to Linux.  

I am aware that it is not listed as a dependency, but I found the resolution of adding Microsoft.ApplicationInsights.AzureWebSites in another issue listed somewhere else.  I can't find the issue (perhaps stackoverflow).  It said that the issue is resolved by either adding Microsoft.ApplicationInsights.AzureWebSites or using the site extension.  The site extension works and I cannot add the reference to this.

**Comment by cijothomas** [comment] 2019-02-27 22:55
The right way to enable application insights if you are deploying to linux is this:
1. Add Microsoft.ApplicationInsights.AspNetCore package.
2 .Enable application insights either via UseApplicationInsights() or AddApplicationInsightsTelemetry() extension methods.
3. deploy

If you face issues following the above steps - i can help with that.

(Microsoft.ApplicationInsights.AzureWebSites is a site extension so I dont know why would you want to install it locally anyway)

**Comment by gckeller-ps** [comment] 2019-02-27 23:02
That is exactly what I did.  I understand that it's a site extension, but Linux does not support site extensions hence why I need the package reference.

**Comment by gckeller-ps** [comment] 2019-02-27 23:03
I also circulated this within our org and about 20 other developers were able to reproduce this.

**Comment by cijothomas** [comment] 2019-02-27 23:08
I am not repro ing this.
Do you have extension installed on your app service?

**Comment by gckeller-ps** [comment] 2019-02-27 23:15
Linux doesn't support Site Extensions so no.  Please understand the significance of this.  In a nutshell, if you want to profile using application insights deployed in .NET core on Linux, you can't.  Are you deployed to a Linux App Service?  If you have the site extension installed, my guess is no.  I am out right now, but can help you reproduce in about an hour if you're down.  I believe you can reproduce the same behavior by removing the site extension on a Windows deployment.

**Comment by cijothomas** [comment] 2019-02-27 23:18
I have deployed to App Service Windows (with/without extension), and i don't face the issue.

**Comment by gckeller-ps** [comment] 2019-02-27 23:19
Try Linux

**Comment by gckeller-ps** [comment] 2019-02-27 23:23
If that doesn't work, i'll repro when I get home and send you my references.   Note with Linux, you either need to use Core 2.1 or a docker container unless 2.2 is supported yet.

**Comment by cijothomas** [comment] 2019-02-27 23:31
Your original description says windows or linux, and .net core 2.2.
Anyway i have deployed to app service in linux and sdk works just fine. So no repro for me.
![image](https://user-images.githubusercontent.com/5232798/53530469-cbd08a00-3aa4-11e9-8844-ff3d50d30c8a.png)

**Comment by gckeller-ps** [comment] 2019-02-27 23:34
I'll try to repro in both and also try to locate the other issue with folks experiencing the same problem and get back to you.  Thanks for your efforts and assistance.

**Comment by gckeller-ps** [comment] 2019-02-28 00:14
I'm home and on it.  I'll cleanup my status comments once we figure this out.

**Comment by gckeller-ps** [comment] 2019-02-28 00:48
I believe that this is where I got the reference to Microsoft.ApplicationInsights.AspNetCore: https://github.com/aspnet/AspNetCore/issues/5919

It appears that adding the reference to the assembly that you can't add a reference to resolved the problem for this person, but I didn't see anyone deploying to Linux (also, I know the extension works): 
![resolution](https://user-images.githubusercontent.com/46789865/53533317-74dcac00-3ac8-11e9-9e16-f253ce9e1c53.jpg)

It also looks like there was still people with the problem and the ticket was closed being unrelated to the original cause.

**Comment by gckeller-ps** [comment] 2019-02-28 01:01
Looks like the resolution to this was the same resolution as the direction that you gave me on the Long File Path issue:
![image](https://user-images.githubusercontent.com/46789865/53533843-67282600-3aca-11e9-97aa-350657116418.png)

**Comment by cijothomas** [comment] 2019-02-28 15:27
Microsoft.ApplicationInsights.AspNetCore is the official SDK for asp.net core.

I am closing this issue. If you have specific questions, please let us know

**Closed by cijothomas** 2019-02-28 15:27 UTC

**Comment by gckeller-ps** [comment] 2019-02-28 15:48
I get that, but it throws the exceptions requiring the other library.  What was the resolution to this?  Other people are obviously having the same problem and were also directed to open a ticket here.  If this is not the place for the ticket, where is the proper place for the ticket?

**Comment by cijothomas** [comment] 2019-02-28 15:53
Please post the exact repro steps - I don't have any repro. And won't be able to do any investigation without a repro.

**Comment by gckeller-ps** [comment] 2019-02-28 16:39
Ok, I started to try to reproduce on the windows side, but when I went to turn off the extension, the UI explicitly states that the SDK won't profile using the SDK from code.  Which therefore, I believe we can safely conclude that because Linux doesn't support site extensions that you can't use App Insights profiling or snapshot on Linux because the only way would be from code.  Would you concur?  If so, documentation should be updated to reflect this limitation.  If not, I'll setup a Linux environment again to give you repro steps.
![image](https://user-images.githubusercontent.com/46789865/53582084-d0507d80-3b4c-11e9-836e-21c83a3b96f2.png)

**Comment by cijothomas** [comment] 2019-02-28 17:26
Sorry I am not sure what is the issue you want me to investigate here.
Please be very specific - are you using SDK and you are not able to see telemetry? are you using extension and you are not seeing telemetry? And what is the "problem you are reproduced on windows side" ? 

SDK does not do "Profiling" - Profiler is a different tool, and is enabled only from extension. This repo is for asp.net core SDK issues. While I can't help with Profiler issues - I can definitely help find the right people to help.

**Comment by gckeller-ps** [comment] 2019-02-28 17:31
The title of the issue says it all "Application Insights Profiling in .NET Core does not work when using 'Microsoft.ApplicationInsights.AspNetCore' "  On the windows side, the UI explicitly states that it won't work unless you use the Site Extension (i.e. not the Nuget Package).  In Linux Site Extensions aren't supported.   So, I guess I just need you to confirm that you can't use Application Insights Profiling on Linux as is my experience based on the details described in the description.

**Comment by pharring** [comment] 2019-02-28 17:35
I'm also confused. Particularly the repeated mentioning of profiling, yet the "Actual Behavior" talks about hosting startup exceptions.

Are you trying to do use the Application Insights Profiler on Linux to find performance bottlenecks? If so, there's a dedicated repo and nuget for that. Start here: https://github.com/Microsoft/ApplicationInsights-Profiler-AspNetCore
Cc: @xiaomi7732 for Linux profiler.

On Windows, the Application Insights Profiler uses ETW-style profiling which is fully supported on both .NET and .NET Core apps and is controlled via the site extension.

As has been stated, Linux App Services do not support site extensions, so I presume the exceptions described in "actual behavior" are for Windows:
Cc: @clguimanMSFT for hosting startup issues.

**Comment by cijothomas** [comment] 2019-02-28 17:36
Just searched online and found this doc: 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/profiler
It also has instructions for linux. Can you check if this helps?

**Comment by gckeller-ps** [comment] 2019-02-28 17:37
> Just searched online and found this doc:
> https://docs.microsoft.com/en-us/azure/azure-monitor/app/profiler
> It also has instructions for linux. Can you check if this helps?

That is specific to windows as it uses Site Extensions.

**Comment by cijothomas** [comment] 2019-02-28 17:39
It does talk about linux:
![image](https://user-images.githubusercontent.com/5232798/53586296-b149ef80-3b3c-11e9-9535-751e83d803a3.png)

Actual link: https://docs.microsoft.com/en-us/azure/azure-monitor/app/profiler-aspnetcore-linux

**Comment by cijothomas** [comment] 2019-02-28 17:40
oh thanks @pharring - i was about to ask around to find the repo for profiler!

**Comment by gckeller-ps** [comment] 2019-02-28 17:40
> I'm also confused. Particularly the repeated mentioning of profiling, yet the "Actual Behavior" talks about hosting startup exceptions.
> Are you trying to do use the Application Insights Profiler on Linux to find performance bottlenecks? If so, there's a dedicated repo and nuget for that. Start here: https://github.com/Microsoft/ApplicationInsights-Profiler-AspNetCore
> Cc: @xiaomi7732 for Linux profiler.
> On Windows, the Application Insights Profiler uses ETW-style profiling which is fully supported on both .NET and .NET Core apps and is controlled via the site extension.
> As has been stated, Linux App Services do not support site extensions, so I presume the exceptions described in "actual behavior" are for Windows:
> Cc: @clguimanMSFT for hosting startup issues.

I will try this.  To avoid confusion, this originated from me following the instructions for Linux profiling and then began to get startup exceptions; hence the exceptions in the description.

**Comment by pharring** [comment] 2019-02-28 17:44
Good, I think we're reaching consensus :-) 
Since this is about Linux profiling, please open further issues in the https://github.com/Microsoft/ApplicationInsights-Profiler-AspNetCore repo.

**Comment by gckeller-ps** [comment] 2019-02-28 17:48
> Good, I think we're reaching consensus :-)
> Since this is about Linux profiling, please open further issues in the https://github.com/Microsoft/ApplicationInsights-Profiler-AspNetCore repo.

K, thanks will do.  Just as a heads up on the documentation front.  These are the steps that I followed that produced the problem and referenced the AspNetCore library rather than the Profiler library.  I guess this article is specific to Windows?  Perhaps this article should be updated to point to the Linux one?

https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-with-Application-Insights-for-ASP.NET-Core

In the meantime, I'll try the profiler Nuget and post any issues to where you directed me.

Thanks for your help
