### ISSUE TITLE
Version 2.0.0 publishing inaccurate response times

### ISSUE THREAD

**Issue by gegana** [Microsoft/ApplicationInsights-aspnetcore#360] opened 2017-03-14 16:59 UTC
We noticed that upgrading our Microsoft.ApplicationInsights.AspNetCore dependency in our services to version 2.0.0 introduced inaccurate response times logged in Application Insights portal. We are seeing response times in the seconds (1-5s), but when we performance test our application we get response times in the milliseconds. We also tried debugging the services and diagnosing the response times via browser network utility, and we see a large discrepancy in what is being published to application insight, and what is recorded in the browser. 

Downgrading the version to 1.0.2 fixes the issue, so it seems like some bug is introduced in version 2.0.0. Unfortunately we want to be using .netcore 1.1, which doesn't support the version 1.0.2, so we really need this to get fixed.

**Comment by billpratt** [comment] 2017-03-14 21:25
Open issue in regards to this: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/350

**Comment by dnduffy** [comment] 2017-05-16 21:31
This should have been fixed in 2.1.0-betas and looks like a duplicate of #350.

**Closed by dnduffy** 2017-05-16 21:31 UTC
Labels: bug
