### ISSUE TITLE
Correct correlation for Microsoft.Azure.Storage.DataMovement

### ISSUE THREAD

**Issue by Planche95** [microsoft/ApplicationInsights-aspnetcore#995] opened 2019-09-26 19:26 UTC
##  Repro Steps
Console App to test correlation for auto tracked events using Data Movement:

```
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.DataContracts;
using Microsoft.Azure.Storage;
using Microsoft.Azure.Storage.Blob;
using Microsoft.Azure.Storage.DataMovement;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using System;
using System.IO;
using System.Net.Http;
using System.Threading.Tasks;

namespace DataMovementTelemetry
{
    public class Program
    {
        private static readonly string _originStorageConnectionString = "fakeValue";
        private static readonly string _originStorageContainerName = "fakeValue";
        private static readonly string _instrumentationKey = "fakeValue";
        private static ILogger<Program> _logger;

        static async Task Main(string[] args)
        {
            IServiceCollection services = new ServiceCollection();
            services.AddApplicationInsightsTelemetryWorkerService(_instrumentationKey);
            IServiceProvider serviceProvider = services.BuildServiceProvider();

            _logger = serviceProvider.GetRequiredService<ILogger<Program>>();
            var telemetryClient = serviceProvider.GetRequiredService<TelemetryClient>();

            using (telemetryClient.StartOperation<RequestTelemetry>("operation"))
            {
                _logger.LogWarning("Warning!");
                var res = await new HttpClient().GetAsync("https://bing.com");
                telemetryClient.TrackEvent("Bing call event completed");

                await DownloadFile("test_file_100MB.mp4");
            }

            using (telemetryClient.StartOperation<RequestTelemetry>("operation"))
            {
                _logger.LogWarning("Warning!");
                var res = await new HttpClient().GetAsync("https://bing.com");
                telemetryClient.TrackEvent("Bing call event completed");

                await DownloadFile("HubbleUltraDeepField.png");
            }

            telemetryClient.Flush();
            Task.Delay(5000).Wait();
        }

        public static async Task DownloadFile(string fileName)
        {
            CloudStorageAccount _storageAccount = CloudStorageAccount.Parse(_originStorageConnectionString);
            CloudBlobClient _blobClient = _storageAccount.CreateCloudBlobClient();
            CloudBlobContainer _container = _blobClient.GetContainerReference(_originStorageContainerName);

            var originBlob = _container.GetBlockBlobReference(fileName);

            var sharedTransferContext = new SingleTransferContext
            {
                ShouldOverwriteCallbackAsync = async (source, destination) => true,
            };

            var options = new DownloadOptions
            {
                DisableContentMD5Validation = true
            };

            string directoryPath = "C:\\Tmp\\Processed";

            if (!Directory.Exists(directoryPath))
                Directory.CreateDirectory(directoryPath);

            var destinationPath = Path.Combine(directoryPath, fileName);

            await TransferManager.DownloadAsync(originBlob, destinationPath, options, sharedTransferContext);
            //originBlob.DownloadToFile(destinationPath, FileMode.OpenOrCreate);
        }
    }
}
```

##  Actual Behavior
Logs and AI for first "operation":
![image](https://user-images.githubusercontent.com/18653765/65718508-f4a11800-e0a3-11e9-99c0-6aa8c9dd8fdf.png)
![image](https://user-images.githubusercontent.com/18653765/65717804-76904180-e0a2-11e9-9555-c4116f83fe95.png)

Logs and AI for the second operation:
![image](https://user-images.githubusercontent.com/18653765/65718532-01be0700-e0a4-11e9-8946-0d7f9408d1e9.png)
![image](https://user-images.githubusercontent.com/18653765/65717759-5b253680-e0a2-11e9-9770-e9ececd68ad8.png)

Parent-Id for Azure Blob operations that comes from Data movement stays the same for all operations. And because of that dependency are not correlated correctly in AI. If I'm not using DataMovement e.g:
`originBlob.DownloadToFile(destinationPath, FileMode.OpenOrCreate);`
instead of:
`await TransferManager.DownloadAsync(originBlob, destinationPath, options,sharedTransferContext);`
parent-id is correct and different.

How to make sure that Parent-Id will be regenerated for each DataMovement Call with different operation scope?

## Version Info 
.NET Core Version: 2.2	 						
How Application was onboarded with SDK: Nuget
OS : Windows 10
Hosting Info: Running From Visual Studio
Nugets:
```
<ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.8.0" />
    <PackageReference Include="Microsoft.Azure.Storage.DataMovement" Version="1.0.0" />
</ItemGroup>
```

**Comment by cijothomas** [comment] 2019-09-26 20:39
@Planche95 Correct me if I understood the question wrong. ParentID for all blob operations are same because they are all done within the scope of 'StartOperation'(). So all those calls are treated as child of the same operation.  From your screenshot of E2E, all are correctly shown correlated as well.

I may have misunderstood your question here - if you expected to see a different behaviour, can you describe what that behaviour is?

**Comment by Planche95** [comment] 2019-09-26 23:11
![image](https://user-images.githubusercontent.com/18653765/65730758-43aa7580-e0c3-11e9-9102-ce48daed81f3.png)
I have started operation twice, so I expect that parentId of blob operations will be different in each "StartOperation()" Scope, just like http calls to "bing.com"

**Comment by cijothomas** [comment] 2019-09-27 00:04
Yes that's expected behavior. All calls inside 1st operation will be parented to that operation, and the ones from 2nd operation to the 2nd operation.

Can you run the following query for each operation (i.e for operationid1 and operationid2) and paste results. Its lot easier for investigation to see all items are correctly parented.

union *
| project timestamp, itemType , operation_Id , operation_ParentId 
| where operation_Id == "operationid"

**Comment by Planche95** [comment] 2019-09-27 06:44
For the first operation:
![image](https://user-images.githubusercontent.com/18653765/65747334-7a9f7c00-e101-11e9-893e-237e40b53aad.png)

For second:
![image](https://user-images.githubusercontent.com/18653765/65747460-bfc3ae00-e101-11e9-9425-bb60d5550658.png)

CustomEvent, Warning from log and Get to bing.com was correlated correctly, only DataMovement operations don't have proper parent-id. It looks like it set up parent-id once and never change it. e.g. if I do something like this:

```
await DownloadFile("HubbleUltraDeepField.png");

using (telemetryClient.StartOperation<RequestTelemetry>("operation"))
{
  _logger.LogWarning("Warning!");
  var res = await new HttpClient().GetAsync("https://bing.com");
  telemetryClient.TrackEvent("Bing call event completed");

  await DownloadFile("HubbleUltraDeepField.png");
}
```
For the first "DownloadFile" I don't startedOperation so parentId was not assigned, and when I look into metrics from second "DownloadFile" inside startedOperation the situation doesn't change and it still doesn't have parent-id!

**Comment by Planche95** [comment] 2019-09-30 13:12
Any updates? Are u able to reproduce the issue?

**Comment by cijothomas** [comment] 2019-09-30 14:49
I couldn't repro with regular storage client. (but you mentioned this in your original post as well).
Will try with datamovement api now.

**Comment by cijothomas** [comment] 2019-10-01 18:23
I got this repro-ed with datamovement library.

**Comment by cijothomas** [comment] 2019-10-04 01:09
@lmolkova Do you know about DataMovement library, and any special cases with that?

**Comment by Planche95** [comment] 2019-10-10 08:14
Any update how to fix that? :)

**Comment by lmolkova** [comment] 2019-10-16 21:44
Looking into the [implementation of DataMovement](https://github.com/Azure/azure-storage-net-data-movement/blob/4b2918bdcb335657b8d427aadb581f89b8db9bed/lib/TransferScheduler.cs), they do put requests into the internal queue and then process requests from the queue.

This does not work well with .NET async context flow (that we leverage for correlation) and Application Insights cannot do anything to fix this. DataMovement library would need to flow execution context to work items to allow .NET correlation mechanisms to work.

So I'm closing this as there is not much we can do here. Feel free to reopen.

**Closed by lmolkova** 2019-10-16 21:44 UTC
Labels: bug

**Comment by EmmaZhu** [comment] 2019-10-22 06:40
@lmolkova 
This is Emma from DataMovement team. I'd need some background about the issue. Could you share mote details on "flow execution context to work items to allow .NET correlation mechanisms to work"?

**Comment by lmolkova** [comment] 2019-10-22 21:32
@EmmaZhu 

.NET (and ApplicationInsights uses [Activity](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activity) based on [AsyncLocal](https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1) for implicit context propagation in-process. 

This works over the execution context supported by .NET and works nicely with async scenarios. It does not work with processing things in queues in background thread.

The way to work it around is to capture `Activity.Current` when item is added to the queue and resetting it when you process item.

Activity.Current is only present when there is a tracing system that lights up instrumentation in .NET,. So if there is no tracing system, you check it for null and do no extra work to propagate/restore it.

Let me know if it helps and if you want to learn more about it.
